ModuleLoader/es-module-loader

package.json
grunt-contrib-uglify was present in both dependencies and devDependencies
which probably wasn't intentional
=> clean up npm dependencies

test/custom-loader.spec.js, test/system.spec.js
Here is the setTimeout clean up
=> test: remove setTimout functions

karma.conf.js
Replace the TRAVIS_BUILD_NUMBER by the TRAVIS_JOB_NUMBER
So saucelabs can make a difference between the jobs in the same build.
It will log "TRAVIS # 6.1" or "TRAVIS # 6.2" instead of just "TRAVIS # 6"
=> chore(travis): better saucelabs name

README.md
Existing link seems to just hang, so I've changed to the one linked to from babel's github repo.
=> Correct link to Babel in Readme

demo/index.html
aka add `.js`. My understanding from the [module id -> address change](https://github.com/google/traceur-compiler/issues/1221) is that we should really be using relative paths here too; is that correct? (though both work)
=> [1.0] Adjust the demo to the latest spec

src/loader.js
Throws because of the use of `Array.prototype.some`. Fixes #321
=> Remove assertion that throws in IE8

src/system.js
When using `<script type="module">` it would be nice to give it a name using something like `<script type="module" name="init-page">` so that it shows up as something other than `<Anonymous Module 1>` in dev tools sources panel.  Plus it would make dynamic scripts specific to the page easily importable and reusable.
=> Added ability to name anonymous modules

src/transpiler.js
This fixes a bug where setting Traceur and/or Babel wasn't happening in
multiple-loader scenarios. Instead of using a closure variable set one
on the loader itself.
Picked a long name to avoid collision. Fixes #347
=> Track whether transpiler has ran with a flag on the Loader

src/loader.js
If you do:
`System.newModule(null)` this code would have thrown without this fix.
=> newModule: only use getOwnPropertyNames if obj != null

src/wrapper-start.js
Hi,
using version 0.16.6. we're getting a 'console undefined' error in IE9.
I've traced it back to this attempt to monkey-patch the console.assert function, which is... well, not working at all ;)
```javascript
if (__global.console)
console.assert = console.assert || function() {};
```
so I replaced it with this:
```javascript
if (!__global.console) {
__global.console = { assert: function() {} };
}
```
Hope, that's all right.
=> Fix console-patching for IE8/9

src/system-fetch.js
=> Byte Order Mark included in fulfilled string from SystemLoader.fetch when executed in node

README.md
=> Explanatory text for 1.0 readme

README.md
as baseURL is no longer referred to in the config docs.
I think this removal/deprecation of baseURL should also be mentioned in the 0.17 release notes.
=> Remove reference to baseURL from Readme

src/transpiler.js
```javascript
// file foo.js
import bar from "bar"
console.log(__moduleName);
```
Without this patch, the code above will output "bar" instead of "foo" if this is the first time "bar" was imported.
=> Restrict scopes of __moduleName

src/system-fetch.js
Following up on the discussion here: https://gitter.im/systemjs/systemjs?at=55af92db9402748911923244
Adding an explicit Accept header allows server side middleware to identify requests made specifically to load modules, and thus to hook into the loader chain on the server side.
This is used in https://github.com/Munter/express-systemjs-translate but could potentially open up for a range of other tools to help optimize the development workflow
=> Add module/x-module-loader-module as Accept header

src/system-fetch.js
In the existing `Error(xhr.statusText + ': ' + url || 'XHR error')` implementation, XHR failures with no statusText yield error messages like `: google.com` since the LHS of the `||` is always truthy. This edit changes that to a slightly-less-cryptic `XHR error: status 0 "": http://google.com` (which yields useful results in a web search), or if there is a statusText, `XHR error: status 403 "Forbidden": http://mydomain.com/page`.
(Feel free to just change it directly in the codebase instead of merging if you prefer different formatting, etc.)
=> Fix confusing error when XHR statusText is blank

src/system-fetch.js
This change prevents the following error in IE if loading an external resource like jQurey.
Tested on IE8 Win7 + IE9 Win7 and fixes the following problem:
```
SCRIPT16389: Unspecified error.
```
=> Add if else condition to prevent unspecified error on IE

src/system-fetch.js
This commit adds a `fetchTextFromURL` strategy using the new fetch API required for service workers. #374
It can be used in a service worker like this:
```js
importScripts('babel-browser.js')
importScripts('es6-module-loader-dev.js')
self.addEventListener('install', function(event) {
event.waitUntil(System.import('sw.jsx').then(function(sw) {
return sw.install(event);
}));
});
// [..]
```
I did not get a reliable test case working registering and unregistering a service worker due to mismatching URL scopes in test runners.
=> Add support for new async fetch API

src/transpiler.js
This addresses https://github.com/systemjs/builder/issues/177 by allowing users to specify that source-maps should not be inlined--builder does not deal with inline maps properly.
=> Do not inline source maps for Typescript if compiler option is explicitly set to false

src/transpiler.js
Previously, Traceur would return an array of errors when several were detected during compilation. The module loader would just report the first. In 0.9.3 though, Tracuer was [updated to instead](https://github.com/google/traceur-compiler/commit/04a4327f0cf5fa263dc410985dc63c563c030985#diff-654825a71bbcba648d7bf62497eaaec7) throw a single [MultipleErrors](https://github.com/google/traceur-compiler/blob/master/src/util/CollectingErrorReporter.js#L17) type that contains all the errors inside it.
The module loader currently just reports "undefined" as the error, as there is no array with elements, making for a rather opaque error when a compilation error occurs.
This modifies it to still throw the first element when dealing with an array for backwards compatibility, but will otherwise throw …
=> Fix for error handling in latest version of traceur

README.md
OK, here's my first stab at this, as discussed in #491. Comments of course welcome. I've removed all the links to other docs until these are (re)written, and all the usage examples until these actually work :-)
Not sure whether you want to keep the existing copyright; neither Luke nor Addy has contributed anything for years. 'Copyright contributors' perhaps?
It might be a good idea to mark 1.0 as deprecated - perhaps rename it too? - and change the master Readme to point to this branch rather than 1.0.
=> New Readme for 0.50

bench/1-register-loading.js, bench/runner.js, core/common.js, core/loader-polyfill.js, core/register-loader.js, package.json, test/3-register-loader.js, test/fixtures/dynamic-modules/basic-exports.js, test/fixtures/dynamic-modules/mixed-bundle.js, test/fixtures/system-register-loader.js
The original plan was to implement `System.registerDynamic` (the wrapper format for CommonJS bundling) as a layer on top of this loader in SystemJS, but it has turned out that due to the complexities of the linking algorithm, performance and also integrating the ideas from the latest TC39, it really is best to combine the implementation with `System.register`.
This is the first step of that work here, pending further testing and performance work.
=> WIP - register dynamic refactoring

core/register-loader.js
A proposed fix for Issue #527.
=> Fix: When loading commonjs modules, named exports after the default export are 'undefined'
